all: 
	javac *.java
run: 	
	java org.junit.runner.JUnitCore SortingTest
	java org.junit.runner.JUnitCore MergeSorterTest
setEnv: 
	export CLASSPATH=.:/home/george/mary-ge/SortingLibrary/Java/src-res/junit-4.12.jar:/home/george/mary-ge/SortingLibrary/Java/src-res/hamcrest-core-1.3.jar
	
