all: 
	javac *.java
run: 	
	java org.junit.runner.JUnitCore SortingTest
	java org.junit.runner.JUnitCore MergeSorterTest
setEnv: 
	export CLASSPATH=.:/home/george/JunitTest/junit-4.12.jar:/home/george/JunitTest/hamcrest-core-1.3.jar
	
