all: 
	javac -d ../class *.java
run: 	
	java org.junit.runner.JUnitCore TestSort
setEnv: 
	export CLASSPATH=.:/home/george/JunitTest/junit-4.12.jar:/home/george/JunitTest/hamcrest-core-1.3.jar:/home/george/mary-ge/SortingLibrary/Java/class
	
